### ISSUE TITLE
arm64-simulator binaries

### ISSUE THREAD

**Issue by partiellkorrekt** [nabto/nabto-api-pod#1]
Is it possible to get a version of this pod that supports the arm64-simulator? We can't move to Nabto Edge and this library prevents us from using the iOS-Simulator as we need to use other libraries as well that don't support the x86_64-simulator.

**Comment by gammelby** [comment]
Hi there,

The pod has supported arm64 simulators for a while! I just double checked:

```
[/tmp/NabtoAPI.xcframework/ios-arm64_x86_64-simulator/NabtoAPI.framework] $ file NabtoAPI 
NabtoAPI: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
NabtoAPI (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
NabtoAPI (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Are you using pod version 4.7.2?

Ulrik

**Comment by partiellkorrekt** [comment]
I am using this library through nabto-ios-client. When I try to compile the app for the simulator, I get the following error:

```
Building for 'iOS-simulator', but linking in dylib ([...]/Pods/NabtoClient/NabtoClient.framework/NabtoClient) built for 'iOS'
```

I downloaded the .framework-file that is linked in the pod spec: https://downloads.nabto.com/assets/nabto-api-pod/4.7.2/NabtoAPI.xcframework.zip and I can see that you are in fact correct that arm64 should be supported.

Do you have any Idea, why this error could be happening?

When I do ```pod install```, I can see the following in ```Pods/Target Support Files/NabtoClient/NabtoClient.(debug|release).xcconfig```:

```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
```

This lead me to believe that arm64-simulators where not supported

**Comment by gammelby** [comment]
The `EXCLUDED_ARCHS` was a workaround until we added arm64 support. So it seems you have some stale cocoapods generated stuff in your project. Try to do a `pod deintegrate` and `pod install` again.

I just tried to build the simple [hello-world](https://github.com/nabto/nabto-ios-helloworld) app and it works fine with the following Podfile (with no trace of `EXCLUDED_ARCHS` anywhere):

```
source 'https://github.com/CocoaPods/Specs.git'

project 'NabtoHelloWorld/NabtoHelloWorld.xcodeproj/'

platform :ios, '14.5'

target 'NabtoHelloWorld' do
  use_frameworks!
  pod 'NabtoClient', '~>7.3.0'
end
```

**Comment by partiellkorrekt** [comment]
I found the issue. I am using react-native and using its minimum platform version of 13.4. So cocoapods wouldn't install any newer version of this library than 7.1.0. Increasing my minimum platform version to 14.5 allowed me to install the latest NabtoClient and successfully compile the app for the simulator.

Thank you for pointing me in the right direction :)

**Comment by gammelby** [comment]
Good you got it resolved - happy to help :-)!
